logging:
  level: INFO
  loggers:
    com.dz.student-dropwizard-demo: DEBUG

server:
  maxThreads: 512
  applicationContextPath: /
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081


mongoHost : localhost
mongoPort : 27017
mongoDB : demo-student
collectionName: student